### ISSUE TITLE
User Domain 구현

### ISSUE THREAD

**Issue by JeekLee** [m1naworld/hanghae-soribaddah-api#20]
## Description
User Domain 구현입니다.

## Todo
- [x] dto 구현
- [x] mapper 구현
- [x] service 구현
- [x] validator 구현

## Etc
Spring Security에서 아직 Authentication을 처리하지 않은 관계로, Domain 구현 이후에도 직접적인 테스트는 어려울 수 있습니다.
JWT 구현 간에 Authentiacation 관련 로직을 추가할 예정입니다. @m1naworld 님께서는, OAuth에도 따로 관련 로직을 추가해주시면 감사하겠습니다.
혹시 해당 이슈 머지 후에 User Login 혹은 SignUp 기능이 필요하신 분들께서는 WebSecurityConfig 파일을 날려버리시면 되겠습니다.

추가적으로 @Valid 혹은 @Validate 어노테이션은 다들 사용해보신 것 같아, 따로 정규표현식 확인하는 Service를 만들어서 구현해보겠습니다.

**Comment by m1naworld** [comment]
감사합니다!

**Comment by Jaekyeong1** [comment]
대박이십니다 !!
