### ISSUE TITLE
댓글 예외처리 오류 수정

### ISSUE THREAD

**Issue by Jaekyeong1** [m1naworld/hanghae-soribaddah-api#46]
## Description
인텔리제이에는 예외처리 문자열이 출력
포스트맨으로는 출력되지 않음

## 재현 과정
어떤 상황에 버그가 발생하는지 작성하세요.

## 예상하는 정상 작동
포스트맨에서 해당 상황에서 에러 메시지가 아닌

JSON형식으로

{
    "msg": "해당 게시글을 찾을 수 없습니다.",
    "statusCode": 404
}

가 출력는것을 기대

## 스크린샷
인텔리제이
![image](https://user-images.githubusercontent.com/114788315/208396192-fa68586d-5190-4310-8ccc-a32baeafed36.png)

포스트맨
![image](https://user-images.githubusercontent.com/114788315/208396228-910d6eac-bc75-44d4-8d75-c7b45d4383d3.png)

**Comment by m1naworld** [comment]
exception Handler 설정해주시면 되겠네요!! 👏🏻
